name: 'LCBench'
num_restarts: 5
raw_samples: 128
batch_size: 1
n_iter: 60
n_init: 2
fid_idx: 7
scale: 1
min_value: 0
negate: False
low_cost: 0
fidelities: [1, 8, 16, 32]
target_fidelity: 32
budget: 300
stopping_criteria: 'budget' # budget or max_iter
max_n_iter: 50
n_repeat: 10
plot_results: True  
