name: 'AugmentedRastrigin'
num_restarts: 5
raw_samples: 128
batch_size: 1
n_iter: 30
n_init: 1
fid_idx: 2
scale: 1
min_value: -110
negate: False
low_cost: 0.2
fidelities: [0.1, 0.5, 0.75, 1.0]
target_fidelity: 1.0
budget: 30
stopping_criteria: 'budget' # budget or max_iter
max_n_iter: 300
n_repeat: 10
plot_results: True  
